language: generic
sudo: required
dist: trusty

before_install:
  # install docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=17.12.0~ce-0~ubuntu
  # install docker-machine
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname
  -s`-`uname -m` >/tmp/docker-machine
- sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  # install docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- docker-compose build installer

script:
- sh bin/installer phpunit --exclude-group=functional
- sh bin/installer create-machine
- sh bin/installer phpunit --group=functional
- sh bin/installer export-traefik
- sh bin/installer deploy-traefik
- if [ -z "${KEEP_MACHINE_AFTER-}" ]; then sh bin/installer uninstall; else true; fi

env:
  global:
    - COCOTTE_MACHINE=cocotte-travis-${TRAVIS_BUILD_ID}
    # DIGITAL_OCEAN_API_TOKEN (set in in repo settings)
    - GIT_COMMIT_ID=${TRAVIS_COMMIT}
    # TRAEFIK_ACME_EMAIL (set in in repo settings)
    # TRAEFIK_UI_HOST (set in in repo settings)
    # TRAEFIK_UI_PASSWORD
    - secure: "BOvjUD/+cHoTSlGKT62Lq9CmGyQHp1guwyCrriJxSpDZevDYmCOZVExCbDS4ocCiYcJT6lMgyiQ56bPkgrgXjRFc5nIzwgVn/cvF1Yd96NHEm+WaFpTLUyz+W3yMC4y3WJw0AOIhbrtbUGwgyQ0so/T6zLWnphML/t8+JGFGLZfVDqMpkUlXIjSYyExD8+oxh3AaEhmiO9jDrDWZJfQ6+iO5S21ofP+5vHpQtfLkMKfTMo8QCDv93wFLBAV201qX85jyCCXM7pl1SM7iGQsODiADWZgrPzhjEpGaQhOzBs3cvO5ZCB0Ht+p1cxwWvNA3kdjqLMa5yGkYq5PPQE7CqqQ6crlBtQCYpaZCJqiMxUqw5rceIydYd7RsvabMqH8PFN7cdHu/wfUFBAg7jRZDqJPN366FcLfWh28OTGjboUHqsKwxZSzwJjkyXayookZumOvWWEbT3TGuxEnlBRUCIEF0nqXy1btaXT3tZE05pNZ42eH9hIlCPIAZ2c/yBV1sIibjgRwH0AQHqf7e1NPhJG6YsroD0eesQKDgcbfKj1M4c2bpRxCLfJlfBGhkebhVE1sGWw4DFsiiY2xHDfmna/tPyKeVCT9i/jtOqsGb0VS3Tna/5X1eQrc9H8fQM+mAuZ2Vi6XFRo8H9puclsxKrWkgMrCunWrcS2BNv5iEvK8="
    - TRAEFIK_UI_USERNAME=traefik
