language: generic
sudo: required
dist: trusty

before_install:
  # install docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=17.12.0~ce-0~ubuntu
  # install docker-machine
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname
  -s`-`uname -m` >/tmp/docker-machine
- sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  # install docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- docker-compose build installer

script:
- sh bin/installer phpunit --exclude-group=functional
- sh bin/installer create-machine
- sh bin/installer phpunit --group=functional
- sh bin/installer export-traefik
- sh bin/installer deploy-traefik
- if [ -z "${KEEP_MACHINE_AFTER-}" ]; then sh bin/installer uninstall; else true; fi

env:
  global:
    - COCOTTE_MACHINE=cocotte-travis-${TRAVIS_BUILD_ID}
    # DIGITAL_OCEAN_API_TOKEN (set in in repo settings)
    - GIT_COMMIT_ID=${TRAVIS_COMMIT}
    # TRAEFIK_ACME_EMAIL (set in in repo settings)
    # TRAEFIK_ACME_ENABLED (set in in repo settings)
    # TRAEFIK_AUTH_BASIC
    - secure: "n2xnNiw8n6+hXydZdLhHgBAwf7fQIGclnZ7puCjE/quEZ4RMcO6DE/x+QkTjJviky1Gr5g2vFpvENQQkEehtWVJhOyka1oDcQqkCSlExrtAWO3EM3dswh1jrDwZ04R1RnKjV51M2aUQRa8fv8ol9B+VpUg/Ye9JwLX22nHridEG883gNQzboFWHgWwtxpO39bX2X/if9u3KOZ020vcI8kPNKhIv4/SzGawB9IeKzhsA6uXkDzK1FcsYUdgyoRCnUki+4OFJWm1VcUqfI1Qdb8oOmAn3D4/mYhQwF+YjHU5qOcWbc/YNeXKb3iQ15e4lBfjX6uUV2apU0lhhd/WvZ5dQChOEu0H9U5mg/zKQmTu+pG/lg9uzcGEd6FDVV+QnTAszzbeuhnIlgFRRjwoQQj9t75Nz46GzV57jQqmTAbHwwHh5lPyq3Lw7W8JdCCgb+ujbIr2wF3wjGQdUqjaScmCtokKEk6pzt0tf3PY4Gx4hE0mNH4Gp4YtgmZo9t87ogLyHkc2L2dlAuPSMi4hdanQKlxOSjzA17nwGs6uRu27BY0ei5zlmFKZuh3Ix4JHlpyjCR+EC8+e4bgHNaL/AO3VZ2Iij57H+cE8s5vw150hJy4pK9av2rwBSCzr17ZZeRr+i5GcFxWn49V9uiUP032SGJsjSlDMgcRpBLjT4+vio="
    # TRAEFIK_UI_HOST (set in in repo settings)
