language: generic
sudo: required
dist: trusty

before_install:
  # install docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=18.03.0~ce-0~ubuntu
  # install docker-machine
- curl -L https://github.com/docker/machine/releases/download/v0.14.0/docker-machine-`uname
  -s`-`uname -m` >/tmp/docker-machine
- sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  # install docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- chmod +x bin/*

jobs:
  include:
    - stage: build docker image
      script:
      - docker-compose pull cocotte || true
      - docker-compose --verbose build cocotte
      - docker images | grep chrif
      - echo "$DOCKER_PASSWORD" | docker login -u chrif --password-stdin
      - docker-compose push cocotte
    - stage: unit-test
      script: ./bin/cmd phpunit --exclude-group=functional
    - stage: install
      script: ./bin/install -n -vvv
    - stage: apps
      script: ./bin/static-site -n -vvv
    - stage: uninstall
      script: if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/cmd console networking -n -vvv --remove ${STATIC_SITE_HOSTNAME}; else true; fi
      script: if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/uninstall -n -vvv; else echo "Machine not removed."; fi

after_script:
  - if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/cmd console networking -n -vvv --remove ${STATIC_SITE_HOSTNAME}; else true; fi
  - if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/uninstall -n -vvv; else echo "Machine not removed."; fi

env:
  global:
    - MACHINE_NAME=cocotte-travis-${TRAVIS_BUILD_ID}
    # DIGITAL_OCEAN_API_TOKEN (set in in repo settings)
    - GIT_COMMIT_ID=${TRAVIS_COMMIT}
    - INSTALLER_VERSION=travis-${TRAVIS_BUILD_ID}
    # STATIC_SITE_HOSTNAME (set in in repo settings)
    - STATIC_SITE_NAMESPACE=static-site
    # TRAEFIK_UI_HOSTNAME (set in in repo settings)
    # TRAEFIK_UI_PASSWORD
    - secure: "vDD7Z8hwwiVC8ervHXFoLQt4SPP1mTqHt2E/SchSxGIqk2WszsvL9NYfgu+cB/6JrxjL/25LcXgqH4qJPXs66I/p0Kx/ALj1RvD/6Pkh3OeDH3fWc6Bgoe90+uiGg5kaP/XtyEiD4lthug7vxOXsW/3W+CEC06jEb9bxvSW54xa38AmbSkZ5LcT+gWMOk2I48HfdmsGS2K6zFacjAexJ2P3TVz46ttDzwE2hB7vWiuhtpPv8BfhvGTKhNgquWOQUdPm2vA+Rx9pY733yl1XXJr/OYlaxrKu5JjimmQV3wMgZMZe4PqrRYIpZo1q7dVdlePwAhU5H57zjkuHMzUDgu0rfCW7S1+cooybrO2BGM0n/Bee5HN549GkFjGhNlvaV/uk0Wu03L9xkwria8OFM9mRLnOuSDHa2GK9TvYZ1RAVB1QsjcApIEIpLS7R5PFxPzVFIaBvPgD1OFhL+CU0BfVtWeGZLV93zxiWkm3fbzP+dMDnzl/Mx+mHe+yBTkGheMelzlHYGGSwY/DDWJ2/i8fc3wgvp0fLV8fhSY3HmAwt3lKnEMjMURt+2zI2/fOMk9WtJF1oxxlMhTYaY2/Dc9OsVpV1rIdjDXY2CmwA7ZxPwmrpxvLFRD7CIAn9HdVHpDpgTkQv/3u7F/7h4/qIiKXmRQjIS4j5Jjykj/NBWHSA="
    - TRAEFIK_UI_USERNAME=admin
