language: php
php:
  - 7.1.16
sudo: required
dist: trusty

before_install:
    # install docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=18.03.1~ce-0~ubuntu
    # install docker-machine
  - curl -L https://github.com/docker/machine/releases/download/v0.14.0/docker-machine-`uname
    -s`-`uname -m` >/tmp/docker-machine
  - sudo install /tmp/docker-machine /usr/local/bin/docker-machine
    # install docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - chmod +x bin/*
  - docker pull chrif/cocotte || true # reuse layers if possible
  - docker-compose build cocotte
  - docker images | grep chrif/cocotte

before_script:
  # install code climate https://github.com/codeclimate/test-reporter
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then chmod +x ./cc-test-reporter; fi
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then ./cc-test-reporter before-build --debug; fi

script:
  # tests
  - ./bin/cmd phpunit --coverage-text --coverage-clover /host/build/logs/clover.xml

#  # the install and apps commands
#  - ./bin/install -n -vvv
#  - ./bin/static-site -n -vvv
#
#  # test local deployment
#  - ./.travis/deploy-dev
#
#  # cleanup
#  - if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/cmd console networking -n -vvv --remove ${STATIC_SITE_HOSTNAME}; else true; fi
#  - if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/uninstall -n -vvv; else echo "Machine not removed."; fi

deploy:
  # push image to docker hub
  - provider: script
    skip_cleanup: true
    script: "echo $DOCKER_PASSWORD | docker login -u chrif --password-stdin && \
            docker tag chrif/cocotte:latest chrif/cocotte:${TRAVIS_TAG} && \
            docker push chrif/cocotte:latest && \
            docker push chrif/cocotte:${TRAVIS_TAG}"
    on:
      tags: true

  # prepare artifacts for github release
  - provider: script
    skip_cleanup: true
    script: "docker save chrif/cocotte:${TRAVIS_TAG} | gzip -c > chrif-cocotte-${TRAVIS_TAG}.tar.gz"
    on:
      tags: true

  # github release
  - provider: releases
    skip_cleanup: true
    file: "chrif-cocotte-${TRAVIS_TAG}.tar.gz"
    api_key: $GITHUB_TOKEN
    on:
      tags: true

after_script:
  # symbolic link to resolve paths in coverage report
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then sudo ln -s $PWD/installer /installer && sudo chown travis:travis /installer; fi
  # https://scrutinizer-ci.com/docs/tools/external-code-coverage/
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover build/logs/clover.xml; fi
  # code climate
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then ./cc-test-reporter after-build --coverage-input-type=clover --exit-code=$TRAVIS_TEST_RESULT --debug; fi

env:
  global:
    # code coverage vars
    # CC_TEST_REPORTER_ID (set in in repo settings)
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    # SCRUTINIZER_TOKEN (set in repo settings)

    # DIGITAL_OCEAN_API_TOKEN (set in in repo settings)
    - COCOTTE_VERSION=${TRAVIS_TAG}
    - GIT_COMMIT_ID=${TRAVIS_COMMIT}
    # GITHUB_TOKEN (set in in repo settings)
    - MACHINE_NAME=cocotte-travis-${TRAVIS_BUILD_ID}
    # STATIC_SITE_HOSTNAME (set in in repo settings)
    - STATIC_SITE_NAMESPACE=static-site
    # TRAEFIK_UI_HOSTNAME (set in in repo settings)
    # TRAEFIK_UI_PASSWORD
    - secure: "vDD7Z8hwwiVC8ervHXFoLQt4SPP1mTqHt2E/SchSxGIqk2WszsvL9NYfgu+cB/6JrxjL/25LcXgqH4qJPXs66I/p0Kx/ALj1RvD/6Pkh3OeDH3fWc6Bgoe90+uiGg5kaP/XtyEiD4lthug7vxOXsW/3W+CEC06jEb9bxvSW54xa38AmbSkZ5LcT+gWMOk2I48HfdmsGS2K6zFacjAexJ2P3TVz46ttDzwE2hB7vWiuhtpPv8BfhvGTKhNgquWOQUdPm2vA+Rx9pY733yl1XXJr/OYlaxrKu5JjimmQV3wMgZMZe4PqrRYIpZo1q7dVdlePwAhU5H57zjkuHMzUDgu0rfCW7S1+cooybrO2BGM0n/Bee5HN549GkFjGhNlvaV/uk0Wu03L9xkwria8OFM9mRLnOuSDHa2GK9TvYZ1RAVB1QsjcApIEIpLS7R5PFxPzVFIaBvPgD1OFhL+CU0BfVtWeGZLV93zxiWkm3fbzP+dMDnzl/Mx+mHe+yBTkGheMelzlHYGGSwY/DDWJ2/i8fc3wgvp0fLV8fhSY3HmAwt3lKnEMjMURt+2zI2/fOMk9WtJF1oxxlMhTYaY2/Dc9OsVpV1rIdjDXY2CmwA7ZxPwmrpxvLFRD7CIAn9HdVHpDpgTkQv/3u7F/7h4/qIiKXmRQjIS4j5Jjykj/NBWHSA="
    - TRAEFIK_UI_USERNAME=admin
