language: generic
sudo: required
dist: trusty

before_install:
  # install docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=17.12.0~ce-0~ubuntu
  # install docker-machine
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname
  -s`-`uname -m` >/tmp/docker-machine
- sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  # install docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- chmod +x bin/*
- docker-compose build installer

script:
- ./bin/installer phpunit --exclude-group=functional
- ./bin/installer create-machine
- ./bin/installer phpunit --group=functional
- ./bin/installer export-traefik
- ./bin/installer deploy-traefik
- ./bin/installer ping-traefik 6
- if [ "${ACME_ENABLED:-true}" = true ]; then ./bin/installer check-certificate ${TRAEFIK_UI_HOST} 6; else echo "Skipping SSL verification"; fi
- ./bin/installer machine-ssh docker logs -t traefik
- ./bin/installer static-template test ${STATIC_TEST_HOST}
- ./bin/installer check-online ${STATIC_TEST_HOST} 6
- if [ "${ACME_ENABLED:-true}" = true ]; then ./bin/installer check-certificate ${STATIC_TEST_HOST} 6; else echo "Skipping SSL verification"; fi
- if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/installer configure-networking --remove ${STATIC_TEST_HOST}; else true; fi
- if [ "${KEEP_MACHINE_AFTER:-false}" = false ]; then ./bin/installer uninstall; else echo "Machine not removed."; fi

env:
  global:
    - COCOTTE_MACHINE=cocotte-travis-${TRAVIS_BUILD_ID}
    # DIGITAL_OCEAN_API_TOKEN (set in in repo settings)
    - GIT_COMMIT_ID=${TRAVIS_COMMIT}
    # STATIC_TEST_HOST (set in in repo settings)
    # TRAEFIK_ACME_EMAIL (set in in repo settings)
    # TRAEFIK_UI_HOST (set in in repo settings)
    # TRAEFIK_UI_PASSWORD
    - secure: "vDD7Z8hwwiVC8ervHXFoLQt4SPP1mTqHt2E/SchSxGIqk2WszsvL9NYfgu+cB/6JrxjL/25LcXgqH4qJPXs66I/p0Kx/ALj1RvD/6Pkh3OeDH3fWc6Bgoe90+uiGg5kaP/XtyEiD4lthug7vxOXsW/3W+CEC06jEb9bxvSW54xa38AmbSkZ5LcT+gWMOk2I48HfdmsGS2K6zFacjAexJ2P3TVz46ttDzwE2hB7vWiuhtpPv8BfhvGTKhNgquWOQUdPm2vA+Rx9pY733yl1XXJr/OYlaxrKu5JjimmQV3wMgZMZe4PqrRYIpZo1q7dVdlePwAhU5H57zjkuHMzUDgu0rfCW7S1+cooybrO2BGM0n/Bee5HN549GkFjGhNlvaV/uk0Wu03L9xkwria8OFM9mRLnOuSDHa2GK9TvYZ1RAVB1QsjcApIEIpLS7R5PFxPzVFIaBvPgD1OFhL+CU0BfVtWeGZLV93zxiWkm3fbzP+dMDnzl/Mx+mHe+yBTkGheMelzlHYGGSwY/DDWJ2/i8fc3wgvp0fLV8fhSY3HmAwt3lKnEMjMURt+2zI2/fOMk9WtJF1oxxlMhTYaY2/Dc9OsVpV1rIdjDXY2CmwA7ZxPwmrpxvLFRD7CIAn9HdVHpDpgTkQv/3u7F/7h4/qIiKXmRQjIS4j5Jjykj/NBWHSA="
    - TRAEFIK_UI_USERNAME=admin
