language: generic
sudo: required
dist: trusty

before_install:
  # install docker
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce=17.12.0~ce-0~ubuntu
  # install docker-machine
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname
  -s`-`uname -m` >/tmp/docker-machine
- sudo install /tmp/docker-machine /usr/local/bin/docker-machine
  # install docker-compose
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

install:
- docker-compose build installer

script:
- sh cocotte.sh create
- sh cocotte.sh remove

env:
  global:
    - MACHINE_NAME=cocotte-travis-${TRAVIS_BUILD_ID}
