version: "2.2"

services:

  cocotte:
    build:
      context: ./installer
      dockerfile: ./Dockerfile
      cache_from:
        - chrif/cocotte
      args:
        - GIT_COMMIT_ID
        - COCOTTE_VERSION
    image: chrif/cocotte
