version: "2"

services:

  cocotte:
    build:
      context: ./installer
      dockerfile: ./Dockerfile
      args:
        - GIT_COMMIT_ID
    image: "chrif/cocotte"

  hostmount:
    image: chrif/cocotte

  dev:
    image: chrif/cocotte
