version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_LOG_DIR=${APP_LOG_DIR}
    image: cocotteapp
    volumes:
      - src:/opt/app
      - log:/opt/log
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8330:8330"
    env_file:
      - .env
      - .env-droplet

volumes:
  src:
  log:
