version: "3"

services:
  nginx:
    build: .
    container_name: "${APP_NAME}nginx"
    restart: always
    volumes:
      - src:/opt/app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${APP_HOSTS}"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default

volumes:
  src:

networks:
  traefik:
    external: true
