parameters:
  api.adapter.class: DigitalOceanV2\Adapter\GuzzleHttpAdapter
  console.output.verbosity: !php/const Symfony\Component\Console\Output\OutputInterface::VERBOSITY_NORMAL

services:
  _defaults:
      autowire: true
      public: true

  # acme
  Cocotte\Acme\CertificateChecker: ~

  # console
  Symfony\Component\Console\Input\InputInterface:
    class: Symfony\Component\Console\Input\ArgvInput
  Symfony\Component\Console\Output\OutputInterface:
    class: Symfony\Component\Console\Output\ConsoleOutput
    arguments:
      - '%console.output.verbosity%'
  Cocotte\Console\Style:
    class: Cocotte\Console\CocotteStyle
  Symfony\Component\Console\Application:
    class: Symfony\Component\Console\Application
    arguments:
      - "<fg=green;options=bold>Cocotte Console</>"
  Cocotte\Command\:
    resource: '../src/Command/*'
    tags: ['console.command']
  Cocotte\Console\InteractionOperator: ~
  Cocotte\Console\OptionProviderRegistry: ~
  Cocotte\Console\OptionProviderAutomation:
    tags: ['event.subscriber']
  Cocotte\Console\HelperFactory: ~
  Symfony\Component\Console\Helper\ProcessHelper:
    factory: 'Cocotte\Console\HelperFactory:processHelper'

  # digital ocean
  Cocotte\DigitalOcean\ApiToken:
    tags: ['lazy.environment']
  Cocotte\DigitalOcean\ApiTokenOptionProvider:
    tags: ['option.provider']
  Cocotte\DigitalOcean\DigitalOceanFactory: ~
  Iodev\Whois\Whois:
    factory: 'Iodev\Whois\Whois::create'
  Cocotte\DigitalOcean\DnsValidator: ~
  Cocotte\DigitalOcean\Domain: ~
  Cocotte\DigitalOcean\DomainRecord: ~
  Cocotte\DigitalOcean\NetworkingConfigurator: ~
  DigitalOceanV2\Adapter\AdapterInterface:
    factory: 'Cocotte\DigitalOcean\DigitalOceanFactory:adapter'
    arguments: ["%api.adapter.class%"]
    lazy: true
  DigitalOceanV2\DigitalOceanV2: ~
  DigitalOceanV2\Api\Droplet: ~
  DigitalOceanV2\Api\Image: ~
  DigitalOceanV2\Api\Region: ~
  DigitalOceanV2\Api\Size: ~
  DigitalOceanV2\Api\Key: ~
  DigitalOceanV2\Api\Domain: ~
  DigitalOceanV2\Api\DomainRecord: ~

  # environment
  Cocotte\Environment\LazyEnvironmentLoader:
    tags: ['event.subscriber']

  # event
  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  # filesystem
  Cocotte\Filesystem\Filesystem:
    class: Cocotte\Filesystem\CocotteFilesystem

  # finder
  Cocotte\Finder\Finder:
    class: Cocotte\Finder\CocotteFinder

  # host
  Cocotte\Host\HostMount:
    tags: ['lazy.environment']
  Cocotte\Host\Mounts:
    tags: ['lazy.environment']
  Cocotte\Host\HostMountRequiredListener:
    tags: ['event.subscriber']

  # machine
  Cocotte\Machine\MachineCreator: ~
  Cocotte\Machine\MachineIp:
    tags: ['lazy.environment']
  Cocotte\Machine\MachineName:
    tags: ['lazy.environment']
  Cocotte\Machine\MachineNameOptionProvider:
    tags: ['option.provider']
  Cocotte\Machine\MachineState: ~
  Cocotte\Machine\MachineStoragePath:
    tags: ['lazy.environment']

  # shell
  Cocotte\Shell\ProcessRunner: ~
  Cocotte\Shell\VariableReplacer: ~
  Cocotte\Shell\EnvironmentSubstitution\SubstitutionFactory: ~
  Cocotte\Shell\BasicAuth: ~

  # template
  ## static site
  Cocotte\Template\StaticSite\StaticSiteCreator: ~
  Cocotte\Template\StaticSite\StaticSiteHostname:
    tags: ['lazy.environment']
  Cocotte\Template\StaticSite\StaticSiteHostnameOptionProvider:
    tags: ['option.provider']
  Cocotte\Template\StaticSite\StaticSiteNamespace:
    tags: ['lazy.environment']
  Cocotte\Template\StaticSite\StaticSiteNamespaceOptionProvider:
    tags: ['option.provider']
  ## traefik
  Cocotte\Template\Traefik\TraefikCreator: ~
  Cocotte\Template\Traefik\TraefikHostname:
    tags: ['lazy.environment']
  Cocotte\Template\Traefik\TraefikHostnameOptionProvider:
    tags: ['option.provider']
  Cocotte\Template\Traefik\TraefikPassword:
    tags: ['lazy.environment']
  Cocotte\Template\Traefik\TraefikPasswordOptionProvider:
    tags: ['option.provider']
  Cocotte\Template\Traefik\TraefikUsername:
    tags: ['lazy.environment']
  Cocotte\Template\Traefik\TraefikUsernameOptionProvider:
    tags: ['option.provider']
  Cocotte\Template\Traefik\TraefikDeploymentValidator: ~

