parameters:
  api.adapter.class: DigitalOceanV2\Adapter\GuzzleHttpAdapter
  console.output.verbosity: !php/const Symfony\Component\Console\Output\OutputInterface::VERBOSITY_NORMAL

services:
  _defaults:
      autowire: true
      public: true

  # environment
  Chrif\Cocotte\Environment\EnvironmentManager: ~

  # console
  Symfony\Component\Console\Input\InputInterface:
    class: Symfony\Component\Console\Input\ArgvInput
  Symfony\Component\Console\Output\OutputInterface:
    class: Symfony\Component\Console\Output\ConsoleOutput
    arguments:
      - '%console.output.verbosity%'
  Chrif\Cocotte\Console\Style:
    class: Chrif\Cocotte\Console\CocotteStyle
  Symfony\Component\Console\Application:
    class: Symfony\Component\Console\Application
    arguments:
      - "Cocotte Console"
  Chrif\Cocotte\Command\:
    resource: '../src/Command/*'
    tags: ['console.command']
  Chrif\Cocotte\Console\InteractionOperator: ~

  # digital ocean
  Chrif\Cocotte\DigitalOcean\ApiToken:
    tags: ['environment']
  Chrif\Cocotte\DigitalOcean\ApiTokenInteraction: ~
  Chrif\Cocotte\DigitalOcean\DigitalOceanFactory: ~
  Iodev\Whois\Whois:
    factory: 'Iodev\Whois\Whois::create'
  Chrif\Cocotte\DigitalOcean\DnsValidator: ~
  Chrif\Cocotte\DigitalOcean\Domain: ~
  Chrif\Cocotte\DigitalOcean\DomainRecord: ~
  Chrif\Cocotte\DigitalOcean\NetworkingConfigurator: ~
  DigitalOceanV2\Adapter\AdapterInterface:
    factory: 'Chrif\Cocotte\DigitalOcean\DigitalOceanFactory:adapter'
    arguments: ["%api.adapter.class%"]
    lazy: true
  DigitalOceanV2\DigitalOceanV2: ~
  DigitalOceanV2\Api\Droplet: ~
  DigitalOceanV2\Api\Image: ~
  DigitalOceanV2\Api\Region: ~
  DigitalOceanV2\Api\Size: ~
  DigitalOceanV2\Api\Key: ~
  DigitalOceanV2\Api\Domain: ~
  DigitalOceanV2\Api\DomainRecord: ~

  # filesystem
  Chrif\Cocotte\Filesystem\Filesystem:
    class: Chrif\Cocotte\Filesystem\CocotteFilesystem

  # finder
  Chrif\Cocotte\Finder\Finder:
    class: Chrif\Cocotte\Finder\CocotteFinder

  Chrif\Cocotte\Host\HostMount:
    tags: ['environment']
  Chrif\Cocotte\Host\Mounts:
    tags: ['environment']

  # machine
  Chrif\Cocotte\Machine\MachineCreator: ~
  Chrif\Cocotte\Machine\MachineIp:
    tags: ['environment']
  Chrif\Cocotte\Machine\MachineName:
    tags: ['environment']
  Chrif\Cocotte\Machine\MachineNameInteraction: ~
  Chrif\Cocotte\Machine\MachineState: ~
  Chrif\Cocotte\Machine\MachineStoragePath:
    tags: ['environment']

  # shell
  Chrif\Cocotte\Shell\ProcessRunner: ~
  Chrif\Cocotte\Shell\VariableReplacer: ~
  Chrif\Cocotte\Shell\EnvironmentSubstitution\SubstitutionFactory: ~
  Chrif\Cocotte\Shell\BasicAuth: ~

  # template
  Chrif\Cocotte\Template\StaticSite\StaticSiteExporter: ~
  Chrif\Cocotte\Template\StaticSite\StaticSiteHostname:
    tags: ['environment']
  Chrif\Cocotte\Template\StaticSite\StaticSiteNamespace:
    tags: ['environment']
  Chrif\Cocotte\Template\Traefik\TraefikExporter: ~
  Chrif\Cocotte\Template\Traefik\TraefikHostname:
    tags: ['environment']
  Chrif\Cocotte\Template\Traefik\TraefikHostnameInteraction: ~
  Chrif\Cocotte\Template\Traefik\TraefikPassword:
    tags: ['environment']
  Chrif\Cocotte\Template\Traefik\TraefikPasswordInteraction: ~
  Chrif\Cocotte\Template\Traefik\TraefikUsername:
    tags: ['environment']
  Chrif\Cocotte\Template\Traefik\TraefikUsernameInteraction: ~
