parameters:
  console.output.verbosity: !php/const Symfony\Component\Console\Output\OutputInterface::VERBOSITY_NORMAL

services:
  _defaults:
      autowire: true
      public: true

  # console
  Symfony\Component\Console\Input\InputInterface:
    class: Symfony\Component\Console\Input\ArgvInput
  Symfony\Component\Console\Output\OutputInterface:
    class: Symfony\Component\Console\Output\ConsoleOutput
    arguments:
      - '%console.output.verbosity%'
  Chrif\Cocotte\Console\Style:
    class: Chrif\Cocotte\Console\CocotteStyle
  Symfony\Component\Console\Application:
    class: Symfony\Component\Console\Application
  Chrif\Cocotte\Wizard\WizardCommand:
    tags: ['console.command']

  # filesystem
  Chrif\Cocotte\Filesystem\Filesystem:
    class: Chrif\Cocotte\Filesystem\CocotteFilesystem

  # dns validation
  Chrif\Cocotte\DigitalOcean\DnsValidator: ~
  Iodev\Whois\Whois:
    factory: 'Iodev\Whois\Whois::create'
