version: '3'

services:
  traefik:
    image: traefik:v1.5.4-alpine
    container_name: traefik
    restart: always
    # http://yaml-multiline.info/
    command: "-c ${APP_TRAEFIK_CONFIG:-/opt/app/traefik.prod.toml} --docker.domain=${DOCKER_DOMAIN:-docker.localhost} --acme.email=${ACME_EMAIL}"
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - src:/opt/app
      - ssl:/opt/ssl
    labels:
    - "traefik.docker.network=traefik"
    - "traefik.enable=true"
    - "traefik.frontend.auth.basic=${APP_AUTH_BASIC}"
    - "traefik.frontend.rule=Host:${APP_HOSTS}"
    - "traefik.port=8081"
    depends_on:
      - data

  data:
    build: .
    image: traefikdata
    volumes:
      - src:/opt/app
      - ssl:/opt/ssl

volumes:
  src:
  ssl:
    external:
      name: traefikssl

networks:
  traefik:
    external: true
