# https://docs.traefik.io/

logLevel = "INFO"
checkNewVersion = true
defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = true

[entryPoints]
	[entryPoints.http]
		address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
		address = ":443"
		[entryPoints.https.tls]

[retry]

[ping]

[api]

[metrics]
	[metrics.statistics]
		recentErrors = 30

[docker]
	exposedbydefault = false
