# https://docs.traefik.io/

logLevel = "INFO"
checkNewVersion = true
defaultEntryPoints = ["http", "https"]
sendAnonymousUsage = true

[entryPoints]
	[entryPoints.http]
		address = ":80"
		[entryPoints.http.redirect]
			entryPoint = "https"
	[entryPoints.https]
		address = ":443"
		[entryPoints.https.tls]
	[entryPoints.api]
		address = ":8080"

[retry]

[api]
	entryPoint = "api"
	[api.statistics]
		RecentErrors = 30

[docker]
	exposedbydefault = false
