# https://docs.traefik.io/

logLevel = "INFO"
checkNewVersion = true
defaultEntryPoints = ["http"]

[entryPoints]
	[entryPoints.http]
		address = ":80"
	[entryPoints.api]
		address = ":8080"

[retry]

[api]
	entryPoint = "api"
	[api.statistics]
		RecentErrors = 30

[docker]
	endpoint = "unix:///var/run/docker.sock"
	watch = true
	exposedbydefault = false
