#!/bin/sh

set -eu

docker-machine -s ${MACHINE_STORAGE_PATH} create \
	--driver digitalocean \
	--digitalocean-access-token ${DIGITAL_OCEAN_API_TOKEN} \
	--engine-opt log-driver="json-file" \
	--engine-opt log-opt="max-size=1m" \
	--engine-opt log-opt="max-file=10" \
	${MACHINE_NAME};
