#!/bin/sh

set -eu

if sh machine-exists | grep 1 > /dev/null; then
    >&2 echo "A machine named ${COCOTTE_MACHINE} already exists. Remove it."
    exit 1;
fi

docker-machine -s ${MACHINE_STORAGE_PATH} create \
	--driver digitalocean \
	--digitalocean-access-token ${DIGITAL_OCEAN_API_TOKEN} \
	--engine-opt log-driver="json-file" \
	--engine-opt log-opt="max-size=1m" \
	--engine-opt log-opt="max-file=10" \
	${COCOTTE_MACHINE} || exit 1;

rsync -rq /installer/traefik /host

rm -rf /host/traefik/.env \
    /host/traefik/.env-override \
    /host/traefik/docker-compose.override.yml \
    /host/traefik/var/*

cat << EOF > /host/traefik/.env
APP_HOSTS=${TRAEFIK_UI_HOST}
APP_AUTH_BASIC='${TRAEFIK_AUTH_BASIC}'
ACME_EMAIL=${TRAEFIK_ACME_EMAIL}
EOF

find /host/traefik -type f -print0 | xargs -0 sed -i "s/\${COCOTTE_MACHINE}/${COCOTTE_MACHINE}/g"
find /host/traefik -type f -print0 | xargs -0 sed -i "s#\${MACHINE_STORAGE_PATH}#${MACHINE_STORAGE_PATH}#g"

console cocotte:configure-networking ${TRAEFIK_UI_HOST}
